// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkSideAPI.Models;

namespace ParkSideAPI.Migrations
{
    [DbContext(typeof(ParkSideAPIContext))]
    [Migration("20191101222305_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkSideAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("Coordinates");

                    b.Property<int>("Established");

                    b.Property<string>("GoverningBody");

                    b.Property<string>("Name");

                    b.Property<string>("StateLocation");

                    b.Property<string>("Website");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Area = "2,219,791 acres",
                            Coordinates = "44°36′N 110°30′W",
                            Established = 1872,
                            GoverningBody = "National Park Service",
                            Name = "Yellowstone National Park",
                            StateLocation = "Wyoming",
                            Website = "https://www.nps.gov/yell/index.htm"
                        },
                        new
                        {
                            ParkId = 2,
                            Area = "49,075.26 acres",
                            Coordinates = "44.35°N 68.21°W",
                            Established = 1919,
                            GoverningBody = "National Park Service",
                            Name = "Acadia National Park",
                            StateLocation = "Maine",
                            Website = "https://www.nps.gov/acad/index.htm"
                        },
                        new
                        {
                            ParkId = 3,
                            Area = "183,224.05 acres",
                            Coordinates = "42.94°N 122.1°W",
                            Established = 1902,
                            GoverningBody = "National Park Service",
                            Name = "Crater Lake National Park",
                            StateLocation = "Oregon",
                            Website = "https://www.nps.gov/crla/index.htm"
                        },
                        new
                        {
                            ParkId = 4,
                            Area = "3,372,981.42  acres",
                            Coordinates = "36.24°N 116.82°W",
                            Established = 1994,
                            GoverningBody = "National Park Service",
                            Name = "Death Valley Lake National Park",
                            StateLocation = "California",
                            Website = "https://www.nps.gov/deva/index.htm"
                        },
                        new
                        {
                            ParkId = 5,
                            Area = "1,013,125.99  acres",
                            Coordinates = "48.80°N 114.00°W",
                            Established = 1910,
                            GoverningBody = "National Park Service",
                            Name = "Glacier Lake National Park",
                            StateLocation = "Montana",
                            Website = "https://www.nps.gov/glac/index.htm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
