// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkSideAPI.Models;

namespace ParkSideAPI.Migrations
{
    [DbContext(typeof(ParkSideAPIContext))]
    [Migration("20191101181907_addSeeding")]
    partial class addSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkSideAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("Coordinates");

                    b.Property<int>("Established");

                    b.Property<string>("GoverningBody");

                    b.Property<string>("Name");

                    b.Property<string>("StateLocation");

                    b.Property<string>("Website");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Area = "2,219,791 acres",
                            Coordinates = "44°36′N 110°30′W",
                            Established = 1872,
                            GoverningBody = "National Park Service",
                            Name = "Yellowstone National Park",
                            StateLocation = "Wyoming",
                            Website = "https://www.nps.gov/yell/index.htm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
